development:
  adapter: postgresql
  database: monster_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: monster_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: monster_production
  pool: 5
  timeout: 5000
